### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by gyrocog** [joomlapro/plg_system_nicescroll#1]
Installed this on Joomla 2.5.16. but it's showing an error...
Error: 500 - JHtml: :jquery not supported. File not found.

If I disable it, the site works normally. Any ideas?

**Comment by brunowego** [comment]
Sorry for not reply.

**Comment by gyrocog** [comment]
@brunowego That's ok. Has anything been done with it?

Just asking out of curiosity, but I can't test it anymore.

**Comment by brunowego** [comment]
Joomla! 2.5 not have support for `JHtml::jquery` static method. Only at 3.x have this support :]
